CREATE TABLE `cpra_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`externalId` varchar(256) NOT NULL,
	`name` varchar(255) NOT NULL,
	`province` varchar(64),
	`city` varchar(128),
	`locationName` varchar(255),
	`locationAddress` varchar(512),
	`startDate` timestamp,
	`endDate` timestamp,
	`entryOpenDate` timestamp,
	`disciplines` text,
	`purseAmount` int,
	`entryFee` int,
	`committeeContact` varchar(255),
	`committeePhone` varchar(64),
	`isSpecialEvent` boolean NOT NULL DEFAULT false,
	`detailsUrl` varchar(512),
	`websiteUrl` varchar(512),
	`rawData` text,
	`scrapedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cpra_events_id` PRIMARY KEY(`id`),
	CONSTRAINT `cpra_events_externalId_unique` UNIQUE(`externalId`)
);
